<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>9.0</LangVersion>
    <AssemblyName>TsqlFormatter.Tests</AssemblyName>
    <RootNamespace>TsqlFormatter.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TsqlFormatter\TsqlFormatter.csproj" />
  </ItemGroup>
</Project>
